Adicionado novos arquivos e alterado pipe

diff --git a/.github/workflows/k8s-pipeline.yml b/.github/workflows/k8s-pipeline.yml
--- a/.github/workflows/k8s-pipeline.yml
+++ b/.github/workflows/k8s-pipeline.yml
@@ -21,6 +21,9 @@ jobs:
       id-token: write 
       contents: read
     steps:
+      - name: Install kubectl
+        uses: azure/setup-kubectl@v2.0
+
       - name: Configure aws credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -30,31 +33,51 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          cli_config_credentials_token: 1.4.6
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v2
+      #   with:
+      #     cli_config_credentials_token: 1.4.6
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+      # - name: Terraform Init
+      #   id: init
+      #   run: terraform init
       
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
+      # - name: Terraform Plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
-        continue-on-error: true
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve -input=false
+      #   continue-on-error: true
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+    
+      - name: Build, tag, and push docker image to Amazon ECR
+        env:
+          REGISTRY: renanfee
+          REPOSITORY: api-valhalla-kitchen
+          IMAGE_TAG: latest
+        run: |
+          docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
+          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
+    
+      - name: Update kube config
+        run: aws eks update-kubeconfig --name primuslearning
+      
+      - name: Deploy to EKS
+        run: |
+          kubectl apply -f kubernets
 
