Pipeline teste

diff --git a/.github/workflows/k8s-pipeline.yml b/.github/workflows/k8s-pipeline.yml
--- a/.github/workflows/k8s-pipeline.yml
+++ b/.github/workflows/k8s-pipeline.yml
@@ -40,44 +40,44 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          cli_config_credentials_token: 1.4.6
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v2
+      #   with:
+      #     cli_config_credentials_token: 1.4.6
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+      # - name: Terraform Init
+      #   id: init
+      #   run: terraform init
       
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate -no-color
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
+      # - name: Terraform Plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
-        continue-on-error: true
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve -input=false
+      #   continue-on-error: true
 
-      - name: Login to Amazon ECR
-        id: login-ecr-aws
-        uses: aws-actions/amazon-ecr-login@v1
+      # - name: Login to Amazon ECR
+      #   id: login-ecr-aws
+      #   uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Create ECR repository
-        env:
-          REPO_NAME: api-valhalla-kitchen
-          REGION: us-east-1
-        run: |
-          aws ecr create-repository --repository-name $REPO_NAME --region $REGION
+      # - name: Create ECR repository
+      #   env:
+      #     REPO_NAME: api-valhalla-kitchen
+      #     REGION: us-east-1
+      #   run: |
+      #     aws ecr create-repository --repository-name $REPO_NAME --region $REGION
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
